[package]
name = "hamcraft"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cli = "0.6.3"

[[bin]]
name = "hamcraft"
path = "src/main.rs"